# Generated by Django 5.2 on 2025-04-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araclar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='arac_resimleri/'),
        ),
    ]
